### ISSUE TITLE
Problem with wormsbynames

### ISSUE THREAD

**Issue by inquil** [janhoo/worms#3]
There is an issue with the scientific names not found by wormsbynames function. Instead of NA it returns an error:

Error in r_parsed[[i]][[1]] : subscript out of bounds

you can test with the example in the readme

taxon_names <- c( "Westwodilla caecula" , "Abra alba", "Chaetozone cf. setosa", "Algae" )
w <- wormsbynames(taxon_names)

Regards,

Carlos

**Comment by janhoo** [comment]
Hi Carlos,

thanks for using worms and thanks for reporting the bug. I will look into
this.
Can you provide a reproducible example.

PS have you checked worrms? It is much better for scraping from WORMS.

best,
J

—

jan m holstein
janmholstein@gmail.com


On 13. April 2018 at 13:38:16, Carlos Canchaya (notifications@github.com)
wrote:

There is an issue with the scientific names not found by wormsbynames
function. Instead of NA it returns an error:

Error in r_parsed[[i]][[1]] : subscript out of bounds

Regards,

Carlos

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/janhoo/worms/issues/3>, or mute the thread

**Comment by inquil** [comment]
Thanks Jan, I put the code in the edited version of mi issue. It is the one
in the readme

Cheers

Carlos

Carlos A.  Canchaya
University of Vigo

**Comment by janhoo** [comment]
Fixed the error and subsequent errors in subsequent functions along the common workflow.
v0.2.2 is on CRAN.

**Comment by PierreENOlivier** [comment]
Hi @janhoo I had the same problem about when this happened.
I had to switch to a different package. Yesterday, I have been advised to use "worms" package again and still having this "Error in r_parsed[[i]][[1]] : subscript out of bounds" issue even with a different data set.
